sudo: required

service:
  - docker

before_install:
  - docker pull michalmoczulski/simple-android-docker

script:
  - docker run --rm  -v $(pwd):/workspace -w /workspace michalmoczulski/simple-android-docker gradle clean build