sudo: required

language: java

service:
  - docker

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - docker pull michalmoczulski/simple-android-docker

script:
  - docker run --rm  -v $(pwd):/workspace -w /workspace michalmoczulski/simple-android-docker gradle clean build

